version: "3"
services:
  web:
    build:
      context: .
      args:
        - SSH_KEY=$SSH_KEY
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'um-user'
      MYSQL_PASSWORD: '6rQR5JNT'
      MYSQL_ROOT_PASSWORD: '6rQR5JNT'
    ports:
      - '3306:3306'
    volumes:
      - graphquiz-db:/var/lib/mysql
volumes:
  graphquiz-db: