version: "3"
services:
  web:
    build: .
    # image: jaspersnel/graph-quiz-test-laravel
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./.env.example:/app/.env

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'umuser'
      MYSQL_PASSWORD: '6rQR5JNT'
      MYSQL_ROOT_PASSWORD: '6rQR5JNT'
    volumes:
      - graphquiz-db:/var/lib/mysql

  reverse_proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./reverse_proxy.conf:/etc/nginx/conf.d/default.conf

volumes:
  graphquiz-db: