version: "3"
services:
  web:
    image: jaspersnel/graph-quiz
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'umuser'
      MYSQL_PASSWORD: '6rQR5JNT'
      MYSQL_ROOT_PASSWORD: '6rQR5JNT'
#     volumes:
#       - graphquiz-db:/var/lib/mysql
# volumes:
#   graphquiz-db:
